import pygame

WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 720
FPS = 60
WALL_WIDTH = WALL_HEIGHT = 32
WALL_COLOR = 'red'
LEVELS_DIR = 'levels'

CAN_SHOOT_EVENT = pygame.USEREVENT + 3
# KILL_PLAYER = pygame.USEREVENT + 4
ADD_BULLETS = []
